# Dependencies
# markdown:         redcarpet
# highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Dylan Lott
tagline:          'Web Developer'
description:      'Developer, designer, coffee addict, beard practitioner, starcraft fanboy, and musician.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Dylan Lott'
  url:            https://twitter.com/dylanlott

paginate:         10

# Custom vars
version:          2.1.0

github:           https://github.com/dylanlott
  repo:           https://github.com/poole/hyde
